### ISSUE TITLE
간헐적으로 네트워크 에러가 뜹니다.

### ISSUE THREAD

**Issue by modforge2** [Kwabang/K-Twitch-Bypass#11]
kt에 엣지 최신버전 사용중입니다.
방송을 보고 있는데 간헐적으로 네트워크 에러#2000이 뜹니다.

처음에는 엣지 자원 절약모드에서만 그런줄 알았는데, 멀쩡히 보다가 그러는 경우도 생기는듯합니다

**Comment by Kwabang** [comment]
크롬 웹스토어 설명에 서술한대로 5~10분 간격으로 트위치에서 CDN을 다시 전환하여 생기는 문제입니다. 해당 문제를 해결하기 위해 패치를 적용하는중입니다.

**Comment by modforge2** [comment]
아 기존 버전이 자동으로 업데이트돼서 못봤습니다 죄송합니다
꾸준히 업데이트해주셔서 정말 감사합니다!
선생님 덕분에 정말 쾌적하게 보고 있어요

**Comment by Kwabang** [comment]
> 아 기존 버전이 자동으로 업데이트돼서 못봤습니다 죄송합니다
> 꾸준히 업데이트해주셔서 정말 감사합니다!
> 선생님 덕분에 정말 쾌적하게 보고 있어요

감사합니다 👏
