### ISSUE TITLE
제가 지금 밴을 당했는데, 무기한 정지  봇 또는 자동 처리된 계정 라고 뜨네요

### ISSUE THREAD

**Issue by jaeminkim-yeet** [Kwabang/K-Twitch-Bypass#17]
정상적으로 만든 계정인데 , 바이패스 쓰고나서, 무기한 정지

봇 또는 자동 처리된 계정

라고 영정이 떴어요ㅠㅠㅠ

**Comment by Kwabang** [comment]
정지 사유가 정확히 어떻게 되나요? 아래와 같은 사유라면 이 확장 프로그램으로 인한 영향이 아닌 다른 문제라고 고려됩니다. 이 확장 프로그램은 아래 행위들을 하지 않습니다.

> 이유
> 봇 또는 자동 처리된 계정
> 봇 또는 자동 처리된 계정으로 원치 않는 광고, 악의적인 링크, 일반 스팸을 대량으로 게시하는 행위.

**Comment by jaeminkim-yeet** [comment]
이게... 보니까 해킹을 당하면 이걸 먹는거 같더라구요, 근데 하필 바이패스를 사용한지 한 하루? 밖에 안돼서 혹시나 이거 때문이 아니였을까? 라고 생각이 들어서 적어봅니다 ㅠㅠ

**Comment by Kwabang** [comment]
트위치에 이의 제기를 추천드립니다.
https://appeals.twitch.tv/
