### ISSUE TITLE
Chrome extension manifest v3 proposal

### ISSUE THREAD

**Issue by kdhkr** [Kwabang/K-Twitch-Bypass#4]
This issue was created as the Chrome Web Store now requires manifest version 3.

"Migrating to Manifest V3" - [https://developer.chrome.com/extensions/migrating_to_manifest_v3](https://developer.chrome.com/extensions/migrating_to_manifest_v3)

**Comment by SaidBySolo** [comment]
https://github.com/Kwabang/Twitch-Tokyo-Server-Fix-Tool/blob/main/chrome/manifest.json
It already supports v3.
I think it's important to check before open an issue.

**Comment by kdhkr** [comment]
Oops sorry my bad :)
