### ISSUE TITLE
오늘부터 네트워크#2000 에러 뜹니다

### ISSUE THREAD

**Issue by modforge2** [Kwabang/K-Twitch-Bypass#6]
찾아보니 도쿄서버 우회해도 720p면 재생이 된다는 말이 있네요
해결해주시면 감사하겠습니다 (_ _)

**Comment by choryuidentify** [comment]
만약 불편하신 분은 잠시동안 'ttvlol' 확장 플러그인을 대신 이용하실 수 있습니다.
다만 러시아 쪽 서버를 사용하는지 방송 딜레이나 버벅임이 있을 수 있습니다.

**Comment by Kwabang** [comment]
해당 이슈를 확인해본결과 트위치측에서 한국에서의 일본 영상 서버 연결 자체를 차단한것을 확인하였습니다. 다른 우회 방법을 찾아볼 예정입니다.

curl "https://video-edge-4ff440.tyo03.abs.hls.ttvnw.net/v1/segment/...ts" -I
HTTP/1.1 403 Forbidden
Access-Control-Allow-Origin: *
Cache-Control: no-cache, no-store, private
Content-Length: 0

**Comment by Kwabang** [comment]
우회 프록시 서버를 서버리스 플랫폼 Verlcel 로 이전하여 이슈를 해결하였습니다.
정상적으로 1080p 시청이 가능하지만 도쿄 서버로 고정되는 것이 아닌 무작위로 다른 국가의 서버로 연결되어 딜레이가 추가적으로 발생할 수 있습니다.
