### ISSUE TITLE
여전히 네트워크#2000 오류가 발생합니다

### ISSUE THREAD

**Issue by choryuidentify** [Kwabang/K-Twitch-Bypass#7]
![image](https://user-images.githubusercontent.com/14815572/211873160-da9b0f91-e859-49f2-a3d6-b4b0062da33e.png)
Firefox 및 MS Edge 로 테스트 하였으나 Firefox 의 경우 위 오류 표출, MS Edge 의 경우 위의 오류가 표출되었다가 바로 로딩 화면으로 전환 된 후 (혹은 아주 잠시동안 스트림이 재생된 후) 다시 오류가 표출하는 사이클을 반복합니다.

참고로 TTV LOL 도 동일한 문제가 있는것으로 보입니다.

[Video.webm](https://user-images.githubusercontent.com/14815572/211874802-bd36bf6d-8d7d-4952-9422-3af5bf38c4ad.webm)

ISP 는 KT 입니다.

**Comment by ghost** [comment]
오늘부터 트위치 쪽에서 국내IP에서 해외 HLS 서버 쪽으로 접근하는걸 아예 막은 것 같네요

**Comment by Kwabang** [comment]
한국을 제외한 다른 국가에서 다른 국가의 접근은 허용되어 있으나, 오직 한국만 다른 국가로의 접근이 차단되었습니다.
한국 -> 다른 국가 (차단)
홍콩 -> 다른 국가 (허용)
일본 -> 다른 국가 (허용)

**Comment by Kwabang** [comment]
현재로선 이렇게 된 이상 VPN으로 시청하는 방법 밖에는 없을 것 같습니다.
